### ISSUE TITLE
Text out of view on Test Connetion screen, no scrollbars

### ISSUE THREAD

**Issue by jerry57** [DICE-UNC/idrop#102]
The Test Connection window has text that is out of view and there are no scrollbars available.  The only saving grace is that users can resize the window to see the missing/obfuscated text.

This was on Mac OS X 10.10 using iDrop downloaded from 
https://github.com/DICE-UNC/idrop/wiki/iDrop-Installers (v2.0.1-RC1)

![screen shot 2015-02-11 at 7 27 02 am](https://cloud.githubusercontent.com/assets/636374/6148546/b5bb69be-b1bf-11e4-9498-f47cc0bf7f79.png)

**Comment by michael-conway** [comment]
Yes, I saw that....I went ahead and pushed to get this installer out the
door.  Was the installer successful there for you now?  Have you tried it
on win64?  I was able to install, run, and do a 14gb transfer with the
timeout set to zero?

MC

**Comment by jerry57** [comment]
I only just started on Mac at this point.  Will try to look at other 
platforms when possible.

jer

On 2/11/15 7:33 AM, Mike Conway wrote:
> Yes, I saw that....I went ahead and pushed to get this installer out the
> door. Was the installer successful there for you now? Have you tried it
> on win64? I was able to install, run, and do a 14gb transfer with the
> timeout set to zero?
>
> MC
>
> On Wed, Feb 11, 2015 at 9:29 AM, Jerry Schneider 
> <notifications@github.com>
> wrote:
>
> > The Test Connection window has text that is out of view and there are no
> > scrollbars available. The only saving grace is that users can resize the
> > window to see the missing/obfuscated text
> >
> > [image: screen shot 2015-02-11 at 7 27 02 am]
> > 
> <https://cloud.githubusercontent.com/assets/636374/6148546/b5bb69be-b1bf-11e4-9498-f47cc0bf7f79.png>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/DICE-UNC/idrop/issues/102>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DICE-UNC/idrop/issues/102#issuecomment-73890005>.
>

-- 
Linux registered user #475536
Ubuntu registered user #28583
