### ISSUE TITLE
iDrop user settings collapsible pane dropdown not working as expected

### ISSUE THREAD

**Issue by jerry57** [DICE-UNC/idrop#103]
Clicking the iDrop user settings dropdown opens up as expected but clicking a second time to collapse while other panels are open does NOT collapse down the panes as expected.  See screenshots
This was with v2.0.1-RC1 from:
https://github.com/DICE-UNC/idrop/wiki/iDrop-Installers
![screen shot 2015-02-11 at 7 39 40 am](https://cloud.githubusercontent.com/assets/636374/6148731/2c467104-b1c1-11e4-8a64-827469f15d6f.png)

![screen shot 2015-02-11 at 7 36 02 am](https://cloud.githubusercontent.com/assets/636374/6148693/edaf2ef4-b1c0-11e4-8a25-265870827ee7.png)
![screen shot 2015-02-11 at 7 36 02 am](https://cloud.githubusercontent.com/assets/636374/6148695/ef9e6f22-b1c0-11e4-9812-9da9096eef3e.png)

**Comment by michael-conway** [comment]
seems a bug in collapsable pane itself.  I found increasing the size of the dialog stops this from occurring.
