### ISSUE TITLE
Several places where text and graphics exceed window or button layout

### ISSUE THREAD

**Issue by jerry57** [DICE-UNC/idrop#112]
I am seeing several locations in the screens where the graphics and text exceed the button or window dimensions.
This was on Mac OS X 10.10.  Windows x64 seems to display correctly.

See attached screenshots for examples:

![screen shot 2015-02-24 at 10 04 49 am](https://cloud.githubusercontent.com/assets/636374/6354860/79d2d202-bc0f-11e4-9766-900fce1f7f42.png)

![screen shot 2015-02-24 at 10 05 07 am](https://cloud.githubusercontent.com/assets/636374/6354861/7eb24df2-bc0f-11e4-96fa-54a3aed3f4ce.png)

**Comment by michael-conway** [comment]
Did a complete pass through all guis, standardizing buttons, fixing some misc layout issues along the way.  

Added 'name' for robots in many places while I was at it.
