### ISSUE TITLE
drag-n-drop download deceiving about actual location to download to

### ISSUE THREAD

**Issue by jerry57** [DICE-UNC/idrop#113]
I drug a directory/collection to the white space in the local tree, expecting it to be downloaded into the root level and it all ended up in the last folder (v2.0.1-RC1-003).  The last folder was NEVER highlighted or touched during the drag operation.

![screen shot 2015-02-24 at 10 42 24 am](https://cloud.githubusercontent.com/assets/636374/6355302/2b8d8d50-bc12-11e4-8e00-e9845d999a9e.png)

**Comment by michael-conway** [comment]
I agree on this one, however, the node that is returned from the tree control at the white space is actually the last node, not the root.  This would require alteration of the tree control code.
