### ISSUE TITLE
File download doesn't even wait for message to be dismissed before beginning transfer

### ISSUE THREAD

**Issue by jerry57** [DICE-UNC/idrop#114]
I dragged a file from iRODS tree to locally mapped drive and got the Confirm a Get dialog.  Before I could even dismiss the dialog I noticed that the Current File transfer bar was progressing along.

![screen shot 2015-02-24 at 10 51 10 am](https://cloud.githubusercontent.com/assets/636374/6355441/4335b7ce-bc13-11e4-88fc-b0a1f770a0b2.png)

Details never even shows the latest transfer.

![screen shot 2015-02-24 at 10 54 38 am](https://cloud.githubusercontent.com/assets/636374/6355484/9b8b8c8c-bc13-11e4-867e-d697b6c0f58f.png)

**Comment by michael-conway** [comment]
cannot replicate.....drag from iRODS tree to local tree waits on dialog interaction in rc1-004 code.
