### ISSUE TITLE
Viewing tree window does not show collection/filenames and NO scrollbar available

### ISSUE THREAD

**Issue by jerry57** [DICE-UNC/idrop#117]
I trying to select an upload sync directory, I was walking the file tree down and noticed that filenames/collection names were truncated so I could no longer make them out.  There was NO scrollbar to expand the window either.

![screen shot 2015-03-10 at 9 37 44 am](https://cloud.githubusercontent.com/assets/636374/6579768/83d30d08-c709-11e4-9170-194a51dbe23f.png)

**Comment by michael-conway** [comment]
You can drag in the header...I will expand the size for the file name by default and I can look at adding a tool tip on the header that can help
