### ISSUE TITLE
Disable iDrop Desktop Client Pass Phrase

### ISSUE THREAD

**Issue by donpellegrino** [DICE-UNC/idrop#118]
For the use case of connecting the iDrop Desktop Client to a single grid using single-sign-on, an iDrop specific pass phrase is not useful. Even in the general case, it seems that operating system level security should be sufficient to secure the connectivity configuration for the iDrop Desktop Client. Therefore, it may improve usability to make the iDrop Desktop Pass Phrase optional or to remove it completely.

**Comment by niravmerchant** [comment]
+1 to that. This has been a fairly common usability issue for our users, as they forget that and have to loose all the grid settings when they reset the pass phrase.
