### ISSUE TITLE
Problem sharing folders by user group 

### ISSUE THREAD

**Issue by lstillwe** [DICE-UNC/idrop#127]
When setting up shared folders by user group - it does not work as expected - noting is shared with all of the users in the group.
This was reported by Raja

**Comment by michael-conway** [comment]
OK it's highly unlikely I can address this in the next couple of days.

**Comment by lstillwe** [comment]
I didn’t expect that you would. Just meant to document it - or I can look into fixing it.
[RENCI]<http://www.renci.org>

Lisa Stillwell
Research Software Developer/GIS Specialist



On Jan 29, 2016, at 1:08 PM, Mike Conway <notifications@github.com<mailto:notifications@github.com>> wrote:

OK it's highly unlikely I can address this in the next couple of days.
