### ISSUE TITLE
iDrop Desktop Installers Win64

### ISSUE THREAD

**Issue by martinjvickers** [DICE-UNC/idrop#129]
In the wiki there are dead links to iDrop Desktop installers. Are there new ones available, specifically for Win64?

**Comment by michael-conway** [comment]
Not immediately, that had been dropped due to lack of resources, but I have
revived it for a current project.  It may thus be ready for an update.

**Comment by martinjvickers** [comment]
Thanks for the swift reply @michael-conway. Do you have install instructions anywhere so I can try to make it myself?

**Comment by michael-conway** [comment]
you can get a demo version of install4j!  That's what we were using to
generate those, and you'll find iinstall4j build files in the git repo for
idrop desktop.  I'm needing to find my keys for that or get a new key to
produce further installs.  Failing that, it is just a java command line
invocation.  I'll try and find an example deployment to show you you can
run it with a simple bat or sh script....

**Comment by martinjvickers** [comment]
The command line invocation would probably be more than enough if you have an example of that.

**Comment by michael-conway** [comment]
Martin sorry to take so long, just back from the UGM.  I'm going to update the master branch with the latest jargon and I'll cut a set of new installers, as I'll be bringing this back into circulation.

**Comment by martinjvickers** [comment]
Hi @michael-conway 
Thanks for getting back to me, I hope the UGM was useful. That's fantastic news about bringing iDROP back into circulation. I think it will be a valuable tool, I will look forward to trying out the new installers.
