### ISSUE TITLE
empty resource list

### ISSUE THREAD

**Issue by jaksat0202** [DICE-UNC/idrop#133]
Hello,
The resource list in the iDrop File Manager comes out empty. It should list the top Resources and it looks like the Query returns 0 rows. The Query can be tested with iquest:

The original Query from the source:
`iquest "SELECT RESC_NAME WHERE RESC_PARENT = ''"`

The correct Query:
`iquest "SELECT RESC_NAME WHERE RESC_PARENT IS NULL"`

Regards,
Jakob

**Comment by jaksat0202** [comment]
The problem occurs only with Oracle and is in the underlying jargon library so I close the issuse here.

**Comment by michael-conway** [comment]
can you add the issue in jargon? It would help if you could assist in
testing this.

**Comment by jaksat0202** [comment]
https://github.com/DICE-UNC/jargon/issues/308
