### ISSUE TITLE
Request for metadata search under top search toolbar option

### ISSUE THREAD

**Issue by PeteClapham** [DICE-UNC/idrop#76]
Hello,
iDROP is looking increasingly promising for our users. Our current usage though is to take heavy advantage of the metadata to locate and curate the data. Without a simple search function our users are unable to find their data.

Could we please request that something like a drop down metadata search option be added 
Many thanks
Pete

**Comment by donpellegrino** [comment]
Are these any releases or beta versions that include a capability to search for files by metadata using a web interface?

**Comment by michael-conway** [comment]
Hi Don, we'll be putting that into milestones for the cloud browser, once we get this first release with basic functionality ready we'll look at prioritizing feature requests.  The highest 'new' feature right now is going to be 'metadata templates' which allow editable, user friendly forms for metadata entry.

**Comment by donpellegrino** [comment]
That is great. I am really looking forward to the new Cloud Browser.
