### ISSUE TITLE
hitting "Enter/Return" key on PassPhrase dialog results in nothing happening

### ISSUE THREAD

**Issue by jerry57** [DICE-UNC/idrop#92]
launch iDrop
at iDrop: Enter Pass Phrase window enter valid passphrase and hit "Enter/Return" key
Note that nothing happens
Users are forced to use mouse and click OK button
The OK button is "selected" based on coloring
see attachment
![screen shot 2015-01-21 at 7 33 30 am](https://cloud.githubusercontent.com/assets/636374/5837837/f5a1205e-a13f-11e4-94b4-2f2f2c10b9c4.png)

**Comment by michael-conway** [comment]
turns out there was an extraneous action listener on the text box that was eating the key press event..  Works now.
