### ISSUE TITLE
Edit Grid and Add Grid should show same fields

### ISSUE THREAD

**Issue by jerry57** [DICE-UNC/idrop#96]
if you open the Grids window by clicking Add button, the fields displayed are:
Host
Port
Zone
User
Password
Default Resource
Starting Collection
Authorization Scheme
Comment

If you select a grid and Click Edit button these fields are displayed:
Host
Port
Zone
User
Password
Confirm Password
Default Resource
Starting Collection
Authorization Scheme
Comment

Note that "Confirm Password" is only on the edit grid window.  If password is critical enough to confirm on edit, shouldn't it be confirmed/creation on entry as well?
See attached screenshots

![add_window](https://cloud.githubusercontent.com/assets/636374/5904448/b2f923be-a545-11e4-89b8-c0f3b13175e5.png)
![edit_window](https://cloud.githubusercontent.com/assets/636374/5904449/b2f93926-a545-11e4-80bd-85503493737c.png)

**Comment by michael-conway** [comment]
yep...agree
