### ISSUE TITLE
iPlant hack fest housekeeping

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/idrop#97]
hack fest at Tucson general issues

**Comment by jerry57** [comment]
Mike here is a list of things I have found so far missing names or other properties

PassPhrase dialog, OK button text has a return after it
Tools Dialog does not have a name
Data Tools dropdown (collapsible panel) does not have a name
Tools Dialog Exit button has no name
Settings Dialog All 4 Collapsible panels are missing names
Test Connection panel does not collapse like other panels on that screen

**Comment by michael-conway** [comment]
OK thanks.

I am working on the connection tester issue as we speak.

**Comment by michael-conway** [comment]
I'll probably refactor this into a set of connection panel issues.  The panel was created 'in code' and I'll probably refactor that to use 'hidden' prepared panels to make it easier to redesign.

**Comment by jerry57** [comment]
More areas/objects missing name/title/tooltip text
PassPhrase dialog/window
- 'Pass Phrase' label missing name
- PassPhrase editbox mising tooltip text
- Welcome back text field missing name
- OK button missing tooltip text
- I Forget button missing tooltip text
- Cancel button missing tooltip text
iDrop: Grid Accounts screen/window
 - Grid Table header row does not have a name assigned (can't verify any of the column names)
iDrop Main window
- Download button missing tooltip text
- Upload button missing tooltip text
- Refresh button missing tooltip text
- New button missing tooltip text
- Copy button missing tooltip text
- Delete button missing tooltip text
- Settings button missing tooltip text
- File Progress bar missing tooltip text
- Transfer Status bar missing tooltip text
- Resource spinner (drop list) missing name
- Resource spinner (drop list) missing tooltip text
- See Details link missing name
- See Details link missing tooltip text
Navigation Dialog
- name is "dialog0" (automatically assigned name and should be static)
Tools Dialog
- name is "dialog0" (automatically assigned name and should be static)
- Data Tools Collapsible pane missing name
- Data Tools Collapsible pane missing tooltip text
Settings Dialog
- IDrop user Settings collapsible pane missing name
- IDrop user Settings collapsible pane missing tooltip text
- Data Transfer Settings collapsible pane missing name
- Data Transfer Settings collapsible pane missing tootip text
- Test Connection collapsible pane missing name
- Test Connection collapsible pane missing tootip text
- Pipeline Configuration collapsible pane missing name
- Pipeline Configuration collapsible pane missing tootip text
