### ISSUE TITLE
text and spinner layout should be same for all collapsible panes in the Settings Dialog

### ISSUE THREAD

**Issue by jerry57** [DICE-UNC/idrop#99]
Open the Settings dialog and then open all of the collapsible panes

Note that several have spinner boxes to select numeric values.  Some of the spinners are right at the end of the text, while others are right justified.  Should use a consistant layout for all, either at end of text or right justified (my preference is for right justified)

See screenshot
![screen shot 2015-02-06 at 9 14 24 am](https://cloud.githubusercontent.com/assets/636374/6082815/450a679c-ade1-11e4-881e-f433f9ad03eb.png)

**Comment by michael-conway** [comment]
agreed.

The current implementation does this all in code, I think we need to reformulate this ticket to make these non-visible panel components to make it easier to configure.
